exp_name: icl_nuim

model: RIENET
dataset: icl_nuim #change it for other datasets
model_path: ''
dim: 16
# -------------------------modelenet40-------------------
rot_factor: 4
gaussian_noise: False
unseen: True

# -------------------------icl_nuim----------------------
max_angle: 45
max_trans: 0.5
data_file_test: ./data/test/icl_nuim.h5
data_file: ./data/train/icl_nuim.h5
clean: False  #change it

# -------------------------7scenes-----------------------
mode: train
mag: 1
workers: 4
dataset-path: ./data/7scene
categoryfile: ./data/categories/7scene_train.txt

# --------------------------kitti-------------------------
voxel_size: 0.3
root: ./data/kitti_dataset/sequences/
data_list: ./data/kitti_list
augment: 1.0


# ----------------model hyper parameters------------------
nn_margin: 0.5  #change
loss_margin: 0.01 #change it for the other datastes
list_k1: [32,32,32] #change it for the other datasets
list_k2: [10,10,10] #change it for the other datasets
emb_dims: 256        # change it for the other datasets
n_iters: 3
n_points: 2048 #2048 for other datasets
n_subsampled_points: 1536 #1536 for other datasets
batch_size: 2
test_batch_size: 2
epochs: 100 # 100 for other datasets
use_sgd: False
n_keypoints: 768 #modelnet40ï¼š 256 others:768
lr: 0.001
momentum: 0.9
no_cuda: False
seed: 1234
start_epoch: 0
lr_step: [25, 50, 75]

# ------------------network training-----------------------
resume: False

# ------------------network testing------------------------
eval: True
